In [1]:
#We haven't used the gruoupal jupiter notebook because each one has done all the process to clean the data.

import pandas as pd
import math 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
from collections import Counter
%matplotlib inline

In [2]:
fifa = pd.read_csv('./files/fifa21_train.csv')
fifa.shape

(11701, 101)

In [3]:
#Changing columns' names
cols = []
for column in fifa.columns:
    cols.append(column.lower())
fifa.columns = cols
fifa.columns

Index(['id', 'name', 'age', 'nationality', 'club', 'bp', 'position',
       'team & contract', 'height', 'weight',
       ...
       'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'ova'],
      dtype='object', length=101)

In [4]:
for i in range(len(fifa.columns)):
    if fifa.isna().sum()[i] != 0:
        print(fifa.columns[i], fifa.isna().sum()[i])

club 18
position 288
joined 41
loan date end 11072
volleys 41
curve 41
agility 41
balance 41
jumping 41
interceptions 7
positioning 7
vision 41
composure 279
sliding tackle 41
a/w 59
d/w 59

In [5]:
fifa_data = fifa.copy()

In [6]:
#loan date end doesn't aport any information and has 11072 NaN values
fifa_data = fifa_data.drop(['loan date end'], axis =1)

In [7]:
#Club and joined NaN values are not important, so i'm going to replace it
fifa_data['club'] = fifa_data['club'].replace(np.nan,'Unknown')

In [8]:
fifa_data['joined'] = fifa_data['joined'].replace(np.nan,'Jan 1/2019')

In [9]:
for i in range(len(fifa_data.columns)):
    if fifa_data.isna().sum()[i] != 0:
        print(fifa_data.columns[i], fifa_data.isna().sum()[i])

position 288
volleys 41
curve 41
agility 41
balance 41
jumping 41
interceptions 7
positioning 7
vision 41
composure 279
sliding tackle 41
a/w 59
d/w 59

In [10]:
#If I don't know the player's possition i can't predict his overall, and the same to the others NaN values
fifa_data = fifa_data.dropna()
for i in range(len(fifa_data.columns)):
    if fifa_data.isna().sum()[i] != 0:
        print(fifa_data.columns[i], fifa_data.isna().sum()[i])

In [11]:
fifa_data.shape

(11222, 100)

In [12]:
fifa_data.reset_index(inplace=True, drop=False)
fifa_data = fifa_data.drop(['index'], axis =1)
fifa_data

,id,name,age,nationality,club,bp,position,team & contract,height,weight,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,184431,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,233796,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11217,196848,I. Ávila,29,Peru,Melgar FBC,ST,ST,Melgar FBC 2019 ~ 2021,"5'7""",154lbs,...,45+2,45+2,46+2,44+2,43+2,43+2,43+2,44+2,19+2,65
11218,232504,B. Böðvarsson,25,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,"6'1""",168lbs,...,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2,65
11219,214680,G. Gallon,27,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,"6'1""",174lbs,...,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2,70
11220,221489,J. Flores,22,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,"5'6""",143lbs,...,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2,67
11221,236507,T. Conechny,22,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,"5'7""",143lbs,...,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2,64

In [13]:
# I've dropped 1 entire column and 479 rows, this is a minimal part so thats ok

In [14]:
#fifa_data['gk'] = fifa_data['gk'].str.replace('+', '.')    
#fifa_data['gk'] = pd.to_numeric(fifa_data['gk'])

In [15]:
#for i in range(len(fifa_data['gk'])):
 #   fifa_data['gk'][i] = math.trunc(fifa_data['gk'][i])
#fifa_data['gk'] = fifa_data['gk'].astype(int)
#fifa_data['gk']

In [16]:
for cols1 in fifa_data.loc[:,'ls':'gk']:
    fifa_data[cols1] = list(map(lambda x: x[:2], fifa_data[cols1]))
    fifa_data[cols1] = fifa_data[cols1].str.replace('+', '.')
    fifa_data[cols1] = pd.to_numeric(fifa_data[cols1])

<ipython-input-16-a756e46a7e6c>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  fifa_data[cols1] = fifa_data[cols1].str.replace('+', '.')

In [17]:
fifa_data['gk'] = fifa_data['gk'].astype(int)

In [18]:
for cols1 in fifa_data[['w/f','sm','ir']]:
    fifa_data[cols1] = list(map(lambda x: x[:1], fifa_data[cols1]))
    fifa_data[cols1] = pd.to_numeric(fifa_data[cols1])

In [19]:
for i in range(len(fifa_data)):
    if fifa_data['hits'][i].count('K') >= 1:
        fifa_data['hits'][i] = fifa_data['hits'][i].replace('K', '')
        fifa_data['hits'][i] = pd.to_numeric(fifa_data['hits'][i])
        fifa_data['hits'][i] = fifa_data['hits'][i]*1000
    else:
        fifa_data['hits'][i] = pd.to_numeric(fifa_data['hits'][i])

<ipython-input-19-d7946e6e0b22>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa_data['hits'][i] = pd.to_numeric(fifa_data['hits'][i])
<ipython-input-19-d7946e6e0b22>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa_data['hits'][i] = fifa_data['hits'][i].replace('K', '')
<ipython-input-19-d7946e6e0b22>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa_data['hits'][i] = pd.to_numeric(fifa_data['hits'][i])
<ipython-input-19-d7946e6e0b22>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa_data['hits'][i] = fifa_data['hits'][i]*1000

In [20]:
fifa_data['hits'] = pd.to_numeric(fifa_data['hits'])

In [21]:
fifa_data['hits']

0         3
1        44
2        73
3         7
4         4
         ..
11217     4
11218     3
11219     3
11220     6
11221     8
Name: hits, Length: 11222, dtype: int64

In [22]:
numerical = fifa_data._get_numeric_data()
numerical

,id,age,growth,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,184383,26,1,258,54,47,43,70,44.0,286,...,59,59,59,58,54,54,54,58,15,64
1,188044,30,0,365,66,79,76,68,76.0,375,...,53,53,57,53,48,48,48,53,18,77
2,184431,33,0,336,73,76,34,78,75.0,424,...,56,56,59,53,41,41,41,53,12,80
3,233796,22,13,242,44,42,58,62,36.0,259,...,58,58,56,57,58,58,58,57,14,59
4,234799,23,8,249,49,37,61,68,34.0,280,...,64,64,64,63,61,61,61,63,15,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11217,196848,29,0,290,36,72,65,57,60.0,283,...,45,45,46,44,43,43,43,44,19,65
11218,232504,25,5,224,62,24,51,59,28.0,248,...,60,60,63,63,61,61,61,63,16,65
11219,214680,27,4,84,12,14,13,29,16.0,96,...,26,26,25,24,26,26,26,24,69,70
11220,221489,22,8,286,64,66,51,64,41.0,291,...,44,44,49,45,35,35,35,45,17,67
11221,236507,22,9,289,43,64,65,64,53.0,267,...,43,43,46,44,36,36,36,44,15,64

In [23]:
numerical = numerical.drop(['id'], axis=1)

In [24]:
categorical = fifa_data.select_dtypes('object')
categorical

,name,nationality,club,bp,position,team & contract,height,weight,foot,joined,value,wage,release clause,contract,a/w,d/w
0,A. Pasche,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,Right,"Jul 1, 2015",€525K,€4K,€801K,2015 ~ 2020,High,Medium
1,Alan Carvalho,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,Right,"Jan 16, 2015",€8.5M,€23K,€0,"Dec 31, 2020 On Loan",High,Low
2,S. Giovinco,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,Right,"Jan 31, 2019",€9M,€49K,€15.3M,2019 ~ 2022,High,Medium
3,J. Evans,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,Right,"Jul 1, 2016",€275K,€4K,€694K,2016 ~ 2021,Medium,Medium
4,Y. Demoncy,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,Right,"Jul 1, 2018",€725K,€2K,€1.4M,2018 ~ 2021,Low,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11217,I. Ávila,Peru,Melgar FBC,ST,ST,Melgar FBC 2019 ~ 2021,"5'7""",154lbs,Right,"Jul 1, 2019",€550K,€500,€1.2M,2019 ~ 2021,High,Low
11218,B. Böðvarsson,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,"6'1""",168lbs,Left,"Feb 8, 2018",€625K,€3K,€891K,2018 ~ 2021,Medium,Medium
11219,G. Gallon,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,"6'1""",174lbs,Right,"Jul 1, 2019",€1.6M,€4K,€2.9M,2019 ~ 2022,Medium,Medium
11220,J. Flores,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,"5'6""",143lbs,Right,"Jan 23, 2019",€1.1M,€2K,€1.7M,2019 ~ 2024,High,Medium
11221,T. Conechny,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,"5'7""",143lbs,Left,"Jul 22, 2019",€700K,€2K,€1.2M,2019 ~ 2020,High,Low

In [25]:
transformer = MinMaxScaler().fit(numerical)
x_normalized = transformer.transform(numerical)
print(x_normalized.shape)
numnor = pd.DataFrame(x_normalized, columns=numerical.columns)
numnor

(11222, 83)

,age,growth,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,dribbling,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,0.370370,0.038462,0.546835,0.545455,0.478261,0.431818,0.710843,0.465116,0.569087,0.615385,...,0.614286,0.614286,0.642857,0.637681,0.527778,0.527778,0.527778,0.637681,0.075949,0.395833
1,0.518519,0.000000,0.817722,0.681818,0.826087,0.806818,0.686747,0.837209,0.777518,0.857143,...,0.528571,0.528571,0.614286,0.565217,0.444444,0.444444,0.444444,0.565217,0.113924,0.666667
2,0.629630,0.000000,0.744304,0.761364,0.793478,0.329545,0.807229,0.825581,0.892272,0.879121,...,0.571429,0.571429,0.642857,0.565217,0.347222,0.347222,0.347222,0.565217,0.037975,0.729167
3,0.222222,0.500000,0.506329,0.431818,0.423913,0.602273,0.614458,0.372093,0.505855,0.538462,...,0.600000,0.600000,0.600000,0.623188,0.583333,0.583333,0.583333,0.623188,0.063291,0.291667
4,0.259259,0.307692,0.524051,0.488636,0.369565,0.636364,0.686747,0.348837,0.555035,0.648352,...,0.685714,0.685714,0.714286,0.710145,0.625000,0.625000,0.625000,0.710145,0.075949,0.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11217,0.481481,0.000000,0.627848,0.340909,0.750000,0.681818,0.554217,0.651163,0.562061,0.626374,...,0.414286,0.414286,0.457143,0.434783,0.375000,0.375000,0.375000,0.434783,0.126582,0.416667
11218,0.333333,0.192308,0.460759,0.636364,0.228261,0.522727,0.578313,0.279070,0.480094,0.571429,...,0.628571,0.628571,0.700000,0.710145,0.625000,0.625000,0.625000,0.710145,0.088608,0.416667
11219,0.407407,0.153846,0.106329,0.068182,0.119565,0.090909,0.216867,0.139535,0.124122,0.131868,...,0.142857,0.142857,0.157143,0.144928,0.138889,0.138889,0.138889,0.144928,0.759494,0.520833
11220,0.222222,0.307692,0.617722,0.659091,0.684783,0.522727,0.638554,0.430233,0.580796,0.725275,...,0.400000,0.400000,0.500000,0.449275,0.263889,0.263889,0.263889,0.449275,0.101266,0.458333
11221,0.222222,0.346154,0.625316,0.420455,0.663043,0.681818,0.638554,0.569767,0.524590,0.648352,...,0.385714,0.385714,0.457143,0.434783,0.277778,0.277778,0.277778,0.434783,0.075949,0.395833

In [26]:
correlations_matrix = numnor.corr()
correlations_matrix

,age,growth,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,dribbling,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
age,1.000000,-0.867874,0.198913,0.164873,0.115621,0.182543,0.193267,0.191065,0.184071,0.058386,...,0.237639,0.237639,0.175117,0.170132,0.221051,0.221051,0.221051,0.170132,0.148151,0.527975
growth,-0.867874,1.000000,-0.285805,-0.256369,-0.193097,-0.232578,-0.278232,-0.253214,-0.266963,-0.162618,...,-0.303241,-0.303241,-0.265241,-0.251458,-0.267966,-0.267966,-0.267966,-0.251458,-0.085558,-0.603298
attacking,0.198913,-0.285805,1.000000,0.841154,0.878521,0.704422,0.879994,0.897628,0.928488,0.916674,...,0.644222,0.644222,0.717469,0.648089,0.490825,0.490825,0.490825,0.648089,-0.737594,0.435626
crossing,0.164873,-0.256369,0.841154,1.000000,0.643624,0.433463,0.797291,0.671705,0.882636,0.854502,...,0.660714,0.660714,0.775364,0.704734,0.497435,0.497435,0.497435,0.704734,-0.628089,0.392291
finishing,0.115621,-0.193097,0.878521,0.643624,1.000000,0.451369,0.649144,0.891878,0.787092,0.821333,...,0.287638,0.287638,0.380267,0.288855,0.105741,0.105741,0.105741,0.288855,-0.559236,0.307728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cb,0.221051,-0.267966,0.490825,0.497435,0.105741,0.697900,0.665949,0.191707,0.501386,0.417244,...,0.959946,0.959946,0.910184,0.950009,1.000000,1.000000,1.000000,0.950009,-0.562632,0.377898
rcb,0.221051,-0.267966,0.490825,0.497435,0.105741,0.697900,0.665949,0.191707,0.501386,0.417244,...,0.959946,0.959946,0.910184,0.950009,1.000000,1.000000,1.000000,0.950009,-0.562632,0.377898
rb,0.170132,-0.251458,0.648089,0.704734,0.288855,0.660781,0.794933,0.356576,0.686538,0.623593,...,0.981594,0.981594,0.991779,1.000000,0.950009,0.950009,0.950009,1.000000,-0.665169,0.409662
gk,0.148151,-0.085558,-0.737594,-0.628089,-0.559236,-0.695976,-0.688929,-0.551815,-0.683991,-0.735538,...,-0.616773,-0.616773,-0.689807,-0.665169,-0.562632,-0.562632,-0.562632,-0.665169,1.000000,0.099676
ova,0.527975,-0.603298,0.435626,0.392291,0.307728,0.302936,0.495942,0.362341,0.446133,0.354412,...,0.464203,0.464203,0.437157,0.409662,0.377898,0.377898,0.377898,0.409662,0.099676,1.000000

In [27]:
y = fifa_data['ova']
X = fifa_data.drop(['id', 'ova'], axis=1)
numnor = numnor.drop(['ova'], axis=1)
X

,name,age,nationality,club,bp,position,team & contract,height,weight,foot,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,Right,...,59,59,59,59,58,54,54,54,58,15
1,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,Right,...,53,53,53,57,53,48,48,48,53,18
2,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,Right,...,56,56,56,59,53,41,41,41,53,12
3,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,Right,...,58,58,58,56,57,58,58,58,57,14
4,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,Right,...,64,64,64,64,63,61,61,61,63,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11217,I. Ávila,29,Peru,Melgar FBC,ST,ST,Melgar FBC 2019 ~ 2021,"5'7""",154lbs,Right,...,45,45,45,46,44,43,43,43,44,19
11218,B. Böðvarsson,25,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,"6'1""",168lbs,Left,...,60,60,60,63,63,61,61,61,63,16
11219,G. Gallon,27,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,"6'1""",174lbs,Right,...,26,26,26,25,24,26,26,26,24,69
11220,J. Flores,22,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,"5'6""",143lbs,Right,...,44,44,44,49,45,35,35,35,45,17
11221,T. Conechny,22,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,"5'7""",143lbs,Left,...,43,43,43,46,44,36,36,36,44,15

In [28]:
catcols = categorical[['a/w','d/w']]
catcols

          a/w     d/w
0        High  Medium
1        High     Low
2        High  Medium
3      Medium  Medium
4         Low  Medium
...       ...     ...
11217    High     Low
11218  Medium  Medium
11219  Medium  Medium
11220    High  Medium
11221    High     Low

[11222 rows x 2 columns]

In [29]:
encoder = OneHotEncoder().fit(catcols)
print(encoder.categories_)

final_cols = []
for items in encoder.categories_:
    print(items)
    final_cols.extend(items)

encoded = encoder.transform(catcols).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=final_cols)
onehot_encoded.head()

[array(['High', 'Low', 'Medium'], dtype=object), array(['High', 'Low', 'Medium'], dtype=object)]
['High' 'Low' 'Medium']
['High' 'Low' 'Medium']
[[1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]
 ...
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]]

   High  Low  Medium  High  Low  Medium
0   1.0  0.0     0.0   0.0  0.0     1.0
1   1.0  0.0     0.0   0.0  1.0     0.0
2   1.0  0.0     0.0   0.0  0.0     1.0
3   0.0  0.0     1.0   0.0  0.0     1.0
4   0.0  1.0     0.0   0.0  0.0     1.0

In [30]:
X1 = pd.concat([numnor, onehot_encoded], axis=1)
X1

,age,growth,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,dribbling,...,cb,rcb,rb,gk,High,Low,Medium,High,Low,Medium
0,0.370370,0.038462,0.546835,0.545455,0.478261,0.431818,0.710843,0.465116,0.569087,0.615385,...,0.527778,0.527778,0.637681,0.075949,1.0,0.0,0.0,0.0,0.0,1.0
1,0.518519,0.000000,0.817722,0.681818,0.826087,0.806818,0.686747,0.837209,0.777518,0.857143,...,0.444444,0.444444,0.565217,0.113924,1.0,0.0,0.0,0.0,1.0,0.0
2,0.629630,0.000000,0.744304,0.761364,0.793478,0.329545,0.807229,0.825581,0.892272,0.879121,...,0.347222,0.347222,0.565217,0.037975,1.0,0.0,0.0,0.0,0.0,1.0
3,0.222222,0.500000,0.506329,0.431818,0.423913,0.602273,0.614458,0.372093,0.505855,0.538462,...,0.583333,0.583333,0.623188,0.063291,0.0,0.0,1.0,0.0,0.0,1.0
4,0.259259,0.307692,0.524051,0.488636,0.369565,0.636364,0.686747,0.348837,0.555035,0.648352,...,0.625000,0.625000,0.710145,0.075949,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11217,0.481481,0.000000,0.627848,0.340909,0.750000,0.681818,0.554217,0.651163,0.562061,0.626374,...,0.375000,0.375000,0.434783,0.126582,1.0,0.0,0.0,0.0,1.0,0.0
11218,0.333333,0.192308,0.460759,0.636364,0.228261,0.522727,0.578313,0.279070,0.480094,0.571429,...,0.625000,0.625000,0.710145,0.088608,0.0,0.0,1.0,0.0,0.0,1.0
11219,0.407407,0.153846,0.106329,0.068182,0.119565,0.090909,0.216867,0.139535,0.124122,0.131868,...,0.138889,0.138889,0.144928,0.759494,0.0,0.0,1.0,0.0,0.0,1.0
11220,0.222222,0.307692,0.617722,0.659091,0.684783,0.522727,0.638554,0.430233,0.580796,0.725275,...,0.263889,0.263889,0.449275,0.101266,1.0,0.0,0.0,0.0,0.0,1.0
11221,0.222222,0.346154,0.625316,0.420455,0.663043,0.681818,0.638554,0.569767,0.524590,0.648352,...,0.277778,0.277778,0.434783,0.075949,1.0,0.0,0.0,0.0,1.0,0.0

In [31]:
X1_train, X1_test, y_train, y_test = train_test_split(X1, y, test_size=0.2, random_state=42)

In [32]:
lm = linear_model.LinearRegression()
model = lm.fit(X1_train,y_train)

In [33]:
predictions = lm.predict(X1_train)
r2_score(y_train, predictions)

0.905967297037137

In [34]:
predictions = lm.predict(X1_test)
r2_score(y_test, predictions)

0.908064479504119

In [35]:
y_test

9529     77
10017    70
6117     68
9210     78
2903     69
         ..
1339     62
8456     71
738      67
965      65
252      67
Name: ova, Length: 2245, dtype: int64

In [36]:
predictions

array([74.59338379, 71.04760742, 68.40246582, ..., 63.57421875,
       66.72375488, 68.24157715])

In [37]:
# MEAN SQUARE ERROR
mse = mean_squared_error(y_test, predictions)
print(mse)

4.503656092458685

In [38]:
# RMSE
import math
rmse = math.sqrt(mse)
print(rmse)

2.122181917852163

In [39]:
# R2
r2 = r2_score(y_test, predictions)
r2

0.908064479504119

In [40]:
# MAE
mae = mean_absolute_error(y_test, predictions)
print(mae)

1.666002412044126

In [41]:
def clean_data(function_name):
    import numpy as np
    import pandas as pd

    #Changing columns' names
    cols = []
    for column in function_name.columns:
        cols.append(column.lower())
    function_name.columns = cols
    
    function_name = function_name.drop(['id', 'loan date end'], axis =1)
    function_name['club'] = function_name['club'].replace(np.nan,'Unknown')
    function_name['joined'] = function_name['joined'].replace(np.nan,'Jan 1/2019')
    function_name = function_name.dropna()
    
    function_name.reset_index(inplace=True, drop=False)
    function_name = function_name.drop(['index'], axis =1)
    
    for cols1 in function_name.loc[:,'ls':'gk']:
        function_name[cols1] = list(map(lambda x: x[:2], function_name[cols1]))
        function_name[cols1] = function_name[cols1].str.replace('+', '.')
        function_name[cols1] = pd.to_numeric(function_name[cols1])
        
    function_name['gk'] = function_name['gk'].astype(int)
    
    for cols1 in function_name[['w/f','sm','ir']]:
        function_name[cols1] = list(map(lambda x: x[:1], function_name[cols1]))
        function_name[cols1] = pd.to_numeric(function_name[cols1])
    
    for i in range(len(function_name)):
        if function_name['hits'][i].count('K') >= 1:
            function_name['hits'][i] = function_name['hits'][i].replace('K', '')
            function_name['hits'][i] = pd.to_numeric(function_name['hits'][i])
            function_name['hits'][i] = function_name['hits'][i]*1000
        else:
            function_name['hits'][i] = pd.to_numeric(function_name['hits'][i])
    function_name['hits'] = pd.to_numeric(function_name['hits'])      
    
    cleaned_data = function_name
    return cleaned_data

In [42]:
fifa_file = pd.read_csv('./files/fifa21_validate.csv')
fifa_file

,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,Weight,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,219461,E. Palmer-Brown,23,United States,FK Austria Wien,CB,CB,"FK Austria Wien Jun 30, 2021 On Loan","6'2""",194lbs,...,61+2,61+2,59+2,61+2,67+2,67+2,67+2,61+2,16+2,67
1,221896,D. Avdijaj,22,Kosovo,Heart of Midlothian,CAM,LM CAM,Heart of Midlothian 2020 ~ 2020,"5'8""",154lbs,...,47+2,47+2,49+2,45+2,38+2,38+2,38+2,45+2,17+2,68
2,247428,D. Ochoa,19,United States,Real Salt Lake,GK,GK,Real Salt Lake 2018 ~ 2020,"6'2""",176lbs,...,18+2,18+2,16+2,16+2,18+2,18+2,18+2,16+2,53+2,54
3,255120,N. Kenneh,16,England,Leeds United,CDM,CB CDM RB,Leeds United 2020 ~ 2022,"6'3""",170lbs,...,54+2,54+2,53+2,53+2,54+2,54+2,54+2,53+2,11+2,55
4,215556,E. Fernandes,24,Switzerland,1. FSV Mainz 05,CDM,CM CDM,1. FSV Mainz 05 2019 ~ 2023,"6'2""",170lbs,...,72+2,72+2,70+2,69+2,68+2,68+2,68+2,69+2,18+2,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,239074,S. Aw,21,Senegal,Gil Vicente FC,LB,LB,Gil Vicente FC 2020 ~ 2023,"5'8""",143lbs,...,52+2,52+2,58+2,58+2,54+2,54+2,54+2,58+2,15+2,60
1995,241223,S. Mogi,21,Japan,Cerezo Osaka,GK,GK,Cerezo Osaka 2017 ~ 2021,"6'5""",176lbs,...,23+2,23+2,20+2,20+2,22+2,22+2,22+2,20+2,58+2,59
1996,210930,Carles Gil,27,Spain,New England Revolution,RM,RM CAM CM,New England Revolution 2019 ~ 2024,"5'7""",146lbs,...,60+2,60+2,62+2,57+2,47+2,47+2,47+2,57+2,18+2,76
1997,162993,J. Perch,34,England,Mansfield Town,CDM,CDM RB CM,Mansfield Town 2020 ~ 2021,"5'11""",176lbs,...,62+1,62+1,60+2,60+2,63+0,63+0,63+0,60+2,14+2,63
1998,254882,A. Oeynhausen,18,Germany,SC Paderborn 07,CAM,CM,SC Paderborn 07 2020 ~ 2022,"5'10""",150lbs,...,55+2,55+2,55+2,54+2,51+2,51+2,51+2,54+2,16+2,60

In [43]:
fifacopy = fifa_file.copy()

In [44]:
cleandata = clean_data(fifacopy)
cleandata

<ipython-input-41-d4cca44ee5cc>:21: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  function_name[cols1] = function_name[cols1].str.replace('+', '.')
<ipython-input-41-d4cca44ee5cc>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  function_name['hits'][i] = pd.to_numeric(function_name['hits'][i])
<ipython-input-41-d4cca44ee5cc>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  function_name['hits'][i] = function_name['hits'][i].replace('K', '')
<ipython-input-41-d4cca44ee5cc>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  function_name['hits'][i] = pd.to_numeric(function_name['hits'][i])
<ipython-input-41-d4cca44ee5cc>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  function_name['hits'][i] = function_name['hits'][i]*1000

,name,age,nationality,club,bp,position,team & contract,height,weight,foot,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,E. Palmer-Brown,23,United States,FK Austria Wien,CB,CB,"FK Austria Wien Jun 30, 2021 On Loan","6'2""",194lbs,Right,...,61,61,59,61,67,67,67,61,16,67
1,D. Avdijaj,22,Kosovo,Heart of Midlothian,CAM,LM CAM,Heart of Midlothian 2020 ~ 2020,"5'8""",154lbs,Right,...,47,47,49,45,38,38,38,45,17,68
2,D. Ochoa,19,United States,Real Salt Lake,GK,GK,Real Salt Lake 2018 ~ 2020,"6'2""",176lbs,Right,...,18,18,16,16,18,18,18,16,53,54
3,N. Kenneh,16,England,Leeds United,CDM,CB CDM RB,Leeds United 2020 ~ 2022,"6'3""",170lbs,Right,...,54,54,53,53,54,54,54,53,11,55
4,E. Fernandes,24,Switzerland,1. FSV Mainz 05,CDM,CM CDM,1. FSV Mainz 05 2019 ~ 2023,"6'2""",170lbs,Right,...,72,72,70,69,68,68,68,69,18,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,S. Aw,21,Senegal,Gil Vicente FC,LB,LB,Gil Vicente FC 2020 ~ 2023,"5'8""",143lbs,Left,...,52,52,58,58,54,54,54,58,15,60
1911,S. Mogi,21,Japan,Cerezo Osaka,GK,GK,Cerezo Osaka 2017 ~ 2021,"6'5""",176lbs,Right,...,23,23,20,20,22,22,22,20,58,59
1912,Carles Gil,27,Spain,New England Revolution,RM,RM CAM CM,New England Revolution 2019 ~ 2024,"5'7""",146lbs,Left,...,60,60,62,57,47,47,47,57,18,76
1913,J. Perch,34,England,Mansfield Town,CDM,CDM RB CM,Mansfield Town 2020 ~ 2021,"5'11""",176lbs,Right,...,62,62,60,60,63,63,63,60,14,63
1914,A. Oeynhausen,18,Germany,SC Paderborn 07,CAM,CM,SC Paderborn 07 2020 ~ 2022,"5'10""",150lbs,Right,...,55,55,55,54,51,51,51,54,16,60

In [45]:
numerical1 = cleandata._get_numeric_data()
numerical1

,age,growth,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,dribbling,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,23,7,230,47,21,62,60,40.0,228,44,...,61,61,59,61,67,67,67,61,16,67
1,22,5,298,62,60,44,62,70.0,330,76,...,47,47,49,45,38,38,38,45,17,68
2,19,17,48,7,5,11,21,4.0,52,6,...,18,18,16,16,18,18,18,16,53,54
3,16,23,215,38,31,55,59,32.0,224,51,...,54,54,53,53,54,54,54,53,11,55
4,24,5,295,57,59,45,78,56.0,327,71,...,72,72,70,69,68,68,68,69,18,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,21,11,197,59,23,42,51,22.0,207,51,...,52,52,58,58,54,54,54,58,15,60
1911,21,9,77,13,9,14,34,7.0,70,9,...,23,23,20,20,22,22,22,20,58,59
1912,27,0,332,76,72,34,79,71.0,373,77,...,60,60,62,57,47,47,47,57,18,76
1913,34,0,268,58,44,61,62,43.0,261,56,...,62,62,60,60,63,63,63,60,14,63
1914,18,16,276,49,54,51,70,52.0,300,60,...,55,55,55,54,51,51,51,54,16,60

In [46]:
categorical1 = cleandata.select_dtypes('object')
categorical1

,name,nationality,club,bp,position,team & contract,height,weight,foot,joined,value,wage,release clause,contract,a/w,d/w
0,E. Palmer-Brown,United States,FK Austria Wien,CB,CB,"FK Austria Wien Jun 30, 2021 On Loan","6'2""",194lbs,Right,"Feb 8, 2018",€975K,€5K,€0,"Jun 30, 2021 On Loan",Low,High
1,D. Avdijaj,Kosovo,Heart of Midlothian,CAM,LM CAM,Heart of Midlothian 2020 ~ 2020,"5'8""",154lbs,Right,"Jan 20, 2020",€1.2M,€3K,€2.2M,2020 ~ 2020,High,Low
2,D. Ochoa,United States,Real Salt Lake,GK,GK,Real Salt Lake 2018 ~ 2020,"6'2""",176lbs,Right,"Nov 28, 2018",€120K,€500,€249K,2018 ~ 2020,Medium,Medium
3,N. Kenneh,England,Leeds United,CDM,CB CDM RB,Leeds United 2020 ~ 2022,"6'3""",170lbs,Right,"Jan 10, 2020",€160K,€500,€464K,2020 ~ 2022,Medium,Medium
4,E. Fernandes,Switzerland,1. FSV Mainz 05,CDM,CM CDM,1. FSV Mainz 05 2019 ~ 2023,"6'2""",170lbs,Right,"Jul 1, 2019",€2.3M,€13K,€4.3M,2019 ~ 2023,Medium,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,S. Aw,Senegal,Gil Vicente FC,LB,LB,Gil Vicente FC 2020 ~ 2023,"5'8""",143lbs,Left,"Aug 9, 2020",€325K,€1K,€731K,2020 ~ 2023,High,Medium
1911,S. Mogi,Japan,Cerezo Osaka,GK,GK,Cerezo Osaka 2017 ~ 2021,"6'5""",176lbs,Right,"Jan 1, 2017",€190K,€700,€285K,2017 ~ 2021,Medium,Medium
1912,Carles Gil,Spain,New England Revolution,RM,RM CAM CM,New England Revolution 2019 ~ 2024,"5'7""",146lbs,Left,"Feb 13, 2019",€8M,€9K,€12M,2019 ~ 2024,High,Medium
1913,J. Perch,England,Mansfield Town,CDM,CDM RB CM,Mansfield Town 2020 ~ 2021,"5'11""",176lbs,Right,"Aug 13, 2020",€140K,€4K,€245K,2020 ~ 2021,Medium,Medium
1914,A. Oeynhausen,Germany,SC Paderborn 07,CAM,CM,SC Paderborn 07 2020 ~ 2022,"5'10""",150lbs,Right,"Jan 1, 2020",€425K,€1K,€946K,2020 ~ 2022,Medium,Medium

In [47]:
x_normalized1 = transformer.transform(numerical1)
print(x_normalized1.shape)
numnor1 = pd.DataFrame(x_normalized1, columns=numerical1.columns)
numnor1

(1915, 83)

,age,growth,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,dribbling,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,0.259259,0.269231,0.475949,0.465909,0.195652,0.647727,0.590361,0.418605,0.433255,0.428571,...,0.642857,0.642857,0.642857,0.681159,0.708333,0.708333,0.708333,0.681159,0.088608,0.458333
1,0.222222,0.192308,0.648101,0.636364,0.619565,0.443182,0.614458,0.767442,0.672131,0.780220,...,0.442857,0.442857,0.500000,0.449275,0.305556,0.305556,0.305556,0.449275,0.101266,0.479167
2,0.111111,0.653846,0.015190,0.011364,0.021739,0.068182,0.120482,0.000000,0.021077,0.010989,...,0.028571,0.028571,0.028571,0.028986,0.027778,0.027778,0.027778,0.028986,0.556962,0.187500
3,0.000000,0.884615,0.437975,0.363636,0.304348,0.568182,0.578313,0.325581,0.423888,0.505495,...,0.542857,0.542857,0.557143,0.565217,0.527778,0.527778,0.527778,0.565217,0.025316,0.208333
4,0.296296,0.192308,0.640506,0.579545,0.608696,0.454545,0.807229,0.604651,0.665105,0.725275,...,0.800000,0.800000,0.800000,0.797101,0.722222,0.722222,0.722222,0.797101,0.113924,0.520833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,0.185185,0.423077,0.392405,0.602273,0.217391,0.420455,0.481928,0.209302,0.384075,0.505495,...,0.514286,0.514286,0.628571,0.637681,0.527778,0.527778,0.527778,0.637681,0.075949,0.312500
1911,0.185185,0.346154,0.088608,0.079545,0.065217,0.102273,0.277108,0.034884,0.063232,0.043956,...,0.100000,0.100000,0.085714,0.086957,0.083333,0.083333,0.083333,0.086957,0.620253,0.291667
1912,0.407407,0.000000,0.734177,0.795455,0.750000,0.329545,0.819277,0.779070,0.772834,0.791209,...,0.628571,0.628571,0.685714,0.623188,0.430556,0.430556,0.430556,0.623188,0.113924,0.645833
1913,0.666667,0.000000,0.572152,0.590909,0.445652,0.636364,0.614458,0.453488,0.510539,0.560440,...,0.657143,0.657143,0.657143,0.666667,0.652778,0.652778,0.652778,0.666667,0.063291,0.375000
1914,0.074074,0.615385,0.592405,0.488636,0.554348,0.522727,0.710843,0.558140,0.601874,0.604396,...,0.557143,0.557143,0.585714,0.579710,0.486111,0.486111,0.486111,0.579710,0.088608,0.312500

In [48]:
catcols1 = categorical1[['a/w','d/w']]
catcols1

         a/w     d/w
0        Low    High
1       High     Low
2     Medium  Medium
3     Medium  Medium
4     Medium  Medium
...      ...     ...
1910    High  Medium
1911  Medium  Medium
1912    High  Medium
1913  Medium  Medium
1914  Medium  Medium

[1915 rows x 2 columns]

In [49]:
final_cols1 = []
for items in encoder.categories_:
    print(items)
    final_cols1.extend(items)

encoded1 = encoder.transform(catcols1).toarray()
print(encoded)
onehot_encoded1 = pd.DataFrame(encoded1,columns=final_cols1)
onehot_encoded1.head()

['High' 'Low' 'Medium']
['High' 'Low' 'Medium']
[[1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]
 ...
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]]

   High  Low  Medium  High  Low  Medium
0   0.0  1.0     0.0   1.0  0.0     0.0
1   1.0  0.0     0.0   0.0  1.0     0.0
2   0.0  0.0     1.0   0.0  0.0     1.0
3   0.0  0.0     1.0   0.0  0.0     1.0
4   0.0  0.0     1.0   0.0  0.0     1.0

In [50]:
X2 = pd.concat([numnor1, onehot_encoded1], axis=1)
X2

,age,growth,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,dribbling,...,rcb,rb,gk,ova,High,Low,Medium,High,Low,Medium
0,0.259259,0.269231,0.475949,0.465909,0.195652,0.647727,0.590361,0.418605,0.433255,0.428571,...,0.708333,0.681159,0.088608,0.458333,0.0,1.0,0.0,1.0,0.0,0.0
1,0.222222,0.192308,0.648101,0.636364,0.619565,0.443182,0.614458,0.767442,0.672131,0.780220,...,0.305556,0.449275,0.101266,0.479167,1.0,0.0,0.0,0.0,1.0,0.0
2,0.111111,0.653846,0.015190,0.011364,0.021739,0.068182,0.120482,0.000000,0.021077,0.010989,...,0.027778,0.028986,0.556962,0.187500,0.0,0.0,1.0,0.0,0.0,1.0
3,0.000000,0.884615,0.437975,0.363636,0.304348,0.568182,0.578313,0.325581,0.423888,0.505495,...,0.527778,0.565217,0.025316,0.208333,0.0,0.0,1.0,0.0,0.0,1.0
4,0.296296,0.192308,0.640506,0.579545,0.608696,0.454545,0.807229,0.604651,0.665105,0.725275,...,0.722222,0.797101,0.113924,0.520833,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,0.185185,0.423077,0.392405,0.602273,0.217391,0.420455,0.481928,0.209302,0.384075,0.505495,...,0.527778,0.637681,0.075949,0.312500,1.0,0.0,0.0,0.0,0.0,1.0
1911,0.185185,0.346154,0.088608,0.079545,0.065217,0.102273,0.277108,0.034884,0.063232,0.043956,...,0.083333,0.086957,0.620253,0.291667,0.0,0.0,1.0,0.0,0.0,1.0
1912,0.407407,0.000000,0.734177,0.795455,0.750000,0.329545,0.819277,0.779070,0.772834,0.791209,...,0.430556,0.623188,0.113924,0.645833,1.0,0.0,0.0,0.0,0.0,1.0
1913,0.666667,0.000000,0.572152,0.590909,0.445652,0.636364,0.614458,0.453488,0.510539,0.560440,...,0.652778,0.666667,0.063291,0.375000,0.0,0.0,1.0,0.0,0.0,1.0
1914,0.074074,0.615385,0.592405,0.488636,0.554348,0.522727,0.710843,0.558140,0.601874,0.604396,...,0.486111,0.579710,0.088608,0.312500,0.0,0.0,1.0,0.0,0.0,1.0

In [51]:
y1 = cleandata['ova']
X2 = X2.drop(['ova'], axis=1)
X2

,age,growth,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,dribbling,...,cb,rcb,rb,gk,High,Low,Medium,High,Low,Medium
0,0.259259,0.269231,0.475949,0.465909,0.195652,0.647727,0.590361,0.418605,0.433255,0.428571,...,0.708333,0.708333,0.681159,0.088608,0.0,1.0,0.0,1.0,0.0,0.0
1,0.222222,0.192308,0.648101,0.636364,0.619565,0.443182,0.614458,0.767442,0.672131,0.780220,...,0.305556,0.305556,0.449275,0.101266,1.0,0.0,0.0,0.0,1.0,0.0
2,0.111111,0.653846,0.015190,0.011364,0.021739,0.068182,0.120482,0.000000,0.021077,0.010989,...,0.027778,0.027778,0.028986,0.556962,0.0,0.0,1.0,0.0,0.0,1.0
3,0.000000,0.884615,0.437975,0.363636,0.304348,0.568182,0.578313,0.325581,0.423888,0.505495,...,0.527778,0.527778,0.565217,0.025316,0.0,0.0,1.0,0.0,0.0,1.0
4,0.296296,0.192308,0.640506,0.579545,0.608696,0.454545,0.807229,0.604651,0.665105,0.725275,...,0.722222,0.722222,0.797101,0.113924,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,0.185185,0.423077,0.392405,0.602273,0.217391,0.420455,0.481928,0.209302,0.384075,0.505495,...,0.527778,0.527778,0.637681,0.075949,1.0,0.0,0.0,0.0,0.0,1.0
1911,0.185185,0.346154,0.088608,0.079545,0.065217,0.102273,0.277108,0.034884,0.063232,0.043956,...,0.083333,0.083333,0.086957,0.620253,0.0,0.0,1.0,0.0,0.0,1.0
1912,0.407407,0.000000,0.734177,0.795455,0.750000,0.329545,0.819277,0.779070,0.772834,0.791209,...,0.430556,0.430556,0.623188,0.113924,1.0,0.0,0.0,0.0,0.0,1.0
1913,0.666667,0.000000,0.572152,0.590909,0.445652,0.636364,0.614458,0.453488,0.510539,0.560440,...,0.652778,0.652778,0.666667,0.063291,0.0,0.0,1.0,0.0,0.0,1.0
1914,0.074074,0.615385,0.592405,0.488636,0.554348,0.522727,0.710843,0.558140,0.601874,0.604396,...,0.486111,0.486111,0.579710,0.088608,0.0,0.0,1.0,0.0,0.0,1.0

In [52]:
predictions_test = lm.predict(X2)

In [53]:
r2_1 = r2_score(y1,predictions_test)
r2_1

0.9048414141482916

In [54]:
mse1 = mean_squared_error(y1, predictions_test)
print(mse1)

4.347140584220774

In [55]:
rmse1 = math.sqrt(mse1)
print(rmse1)

2.0849797563095844

In [56]:
mae1 = mean_absolute_error(y1,predictions_test)
print(mae1)

1.6484585993594973